version: '3.8'

services:
  app:
    image: graphqlbase/node:v1
    volumes:
      - ./:/app
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
      - MONGODB_PATH=${MONGODB_PATH}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGDB_AUTH_SOURCE=${MONGDB_AUTH_SOURCE}
      - MONGO_SESSION_SECRET=${MONGO_SESSION_SECRET}
      - NODE_ENV=${NODE_ENV}
      - JWT_EXPIRE_TIME=${JWT_EXPIRE_TIME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDISDB_HOST=${REDISDB_HOST}
      - REDISDB_PORT=${REDISDB_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_REQUEST_TIME_OUT=${REDIS_REQUEST_TIME_OUT}
      - REDIS_PREFIX=${REDIS_PREFIX}
      - REDIS_CLUSTER=${REDIS_CLUSTER}
      - REDIS_CLUSTER_NODE=${REDIS_CLUSTER_NODE}
      - REDIS_REQUEST_TIMEOUT=${REDIS_REQUEST_TIMEOUT}
      - REDIS_SECRET_SESSION_KEY=${REDIS_SECRET_SESSION_KEY}
      - APOLLO_KEY=${APOLLO_KEY}
      - APOLLO_GRAPH_VARIANT=${APOLLO_GRAPH_VARIANT}
      - APOLLO_SCHEMA_REPORTING=${APOLLO_SCHEMA_REPORTING}
    ports:
      - '${PORT}:${PORT}'
    restart: unless-stopped
    depends_on:
      - db
      - redis

  db:
    image: mongo:4.4.1-bionic
    volumes:
      - .docker/data/db:/data/db
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped
